{
  description = "Portable Paper Minecraft server";

  inputs = {
    nix-minecraft.url = "github:Infinidoge/nix-minecraft";
    nixpkgs.follows = "nix-minecraft/nixpkgs";
  };

  outputs = { self, nixpkgs, nix-minecraft }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
      paperServer = nix-minecraft.packages.${system}.paper-server;
      pluginSymlinks = import ./plugins.nix { inherit pkgs; };
      pluginSymlinkCommands =
        pkgs.lib.concatMapStringsSep "\n" (
          path:
          let
            source = pluginSymlinks.${path};
          in
          ''
            plugin_path=${pkgs.lib.escapeShellArg path}
            plugin_target="$data_dir/$plugin_path"
            mkdir -p "$(dirname "$plugin_target")"
            if [ -e "$plugin_target" ] && [ ! -L "$plugin_target" ]; then
              mv "$plugin_target" "$plugin_target.bak"
            fi
            ln -sfn ${pkgs.lib.escapeShellArg (builtins.toString source)} "$plugin_target"
          ''
        ) (pkgs.lib.attrNames pluginSymlinks);

      mkApp = name: runtimeInputs: text:
        pkgs.writeShellApplication {
          inherit name text;
          runtimeInputs = [ pkgs.coreutils ] ++ runtimeInputs;
        };

      minecraftServer = mkApp "minecraft-server" [ ] ''
        data_dir="''${MINECRAFT_DATA_DIR:-$PWD/server}"
        mkdir -p "$data_dir"
        cd "$data_dir"

        if [ ! -e eula.txt ]; then
          printf 'eula=true\n' > eula.txt
        fi
        if [ ! -e server.properties ]; then
          printf 'level-seed=7979099859567551957\nenforce-secure-profile=false\n' > server.properties
        fi
        ${pluginSymlinkCommands}

        exec ${paperServer}/bin/minecraft-server -Xms1G -Xmx3G "$@"
      '';

      updatePlugins = mkApp "update-plugins" [ pkgs.curl pkgs.jq pkgs.nix ] ''
        repo_dir="$(pwd -P)"
        output="$repo_dir/plugins.nix"
        temporary="$(mktemp "$repo_dir/.plugins.nix.XXXXXX")"
        trap 'rm -f "$temporary"' EXIT

        fetch_modrinth() {
          target="$1"
          project="$2"
          payload="$(curl -fsSL -G -H 'User-Agent: minecraft-flake-plugin-updater/1.0' --data-urlencode 'loaders=["paper"]' "https://api.modrinth.com/v2/project/$project/version")"
          url="$(printf '%s' "$payload" | jq -er 'map(select(.version_type == "release")) | sort_by(.date_published) | last | .files[] | select(.primary) | .url')"
          hash="$(nix store prefetch-file --json --hash-type sha256 --name "$(basename "$target")" "$url" | jq -er .hash)"
          printf '  "%s" = pkgs.fetchurl {\n    url = "%s";\n    hash = "%s";\n  };\n' "$target" "$url" "$hash"
        }

        fetch_treeassist() {
          url="https://slipcor.net/plugins/treeassist/release/latest/TreeAssist.jar"
          hash="$(nix store prefetch-file --json --hash-type sha256 --name TreeAssist.jar "$url" | jq -er .hash)"
          printf '  "plugins/TreeAssist.jar" = pkgs.fetchurl {\n    url = "%s";\n    hash = "%s";\n  };\n' "$url" "$hash"
        }

        {
          printf '%s\n' "# Generated by nix run .#update-plugins."
          printf '%s\n' "# Keys match nix-minecraft's servers.<name>.symlinks declaration format."
          printf '%s\n' '{ pkgs }:' '{'
          fetch_modrinth "plugins/EssentialsX.jar" essentialsx
          fetch_modrinth "plugins/ChestsortPlus.jar" 'chestsort%2B'
          fetch_treeassist
          fetch_modrinth "plugins/SilkSpawners.jar" silkspawners
          fetch_modrinth "plugins/LuckPerms.jar" luckperms
          fetch_modrinth "plugins/InfiniteVillagerTrades.jar" infinite-villager-trading
          printf '%s\n' '}'
        } > "$temporary"

        mv "$temporary" "$output"
        echo "Updated $output. Restart the server to load the new JARs."
      '';

      minecraftTmux = mkApp "minecraft-tmux" [ pkgs.tmux ] ''
        case "''${1:-}" in
          start)
            if tmux has-session -t minecraft 2>/dev/null; then
              exit 0
            fi
            tmux new-session -d -s minecraft "${minecraftServer}/bin/minecraft-server"
            ;;
          stop)
            if ! tmux has-session -t minecraft 2>/dev/null; then
              exit 0
            fi
            tmux send-keys -t minecraft stop C-m
            for _ in $(seq 1 120); do
              if ! tmux has-session -t minecraft 2>/dev/null; then
                exit 0
              fi
              sleep 1
            done
            tmux kill-session -t minecraft
            ;;
          *)
            echo "usage: minecraft-tmux {start|stop}" >&2
            exit 64
            ;;
        esac
      '';

      minecraftConsole = mkApp "minecraft-console" [ pkgs.tmux ] ''
        if ! tmux has-session -t minecraft 2>/dev/null; then
          echo "Minecraft is not running in tmux." >&2
          exit 1
        fi
        exec tmux attach-session -t minecraft
      '';

      installMinecraftService = mkApp "install-minecraft-service" [ pkgs.systemd ] ''
        repo_dir="$(pwd -P)"
        nix_bin="$(command -v nix || true)"
        unit_dir="''${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
        unit_path="$unit_dir/minecraft-server.service"

        if [ -z "$nix_bin" ]; then
          echo "nix was not found in PATH" >&2
          exit 1
        fi

        mkdir -p "$unit_dir"
        cat > "$unit_path" <<EOF
        [Unit]
        Description=Paper Minecraft server
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        WorkingDirectory=$repo_dir
        ExecStart=$nix_bin run --no-write-lock-file "path:$repo_dir#minecraft-tmux" -- start
        ExecStop=$nix_bin run --no-write-lock-file "path:$repo_dir#minecraft-tmux" -- stop
        TimeoutStopSec=130

        [Install]
        WantedBy=default.target
        EOF

        systemctl --user daemon-reload
        systemctl --user enable --now minecraft-server.service
      '';
    in
    {
      packages.${system} = {
        minecraft-server = minecraftServer;
        minecraft-tmux = minecraftTmux;
        minecraft-console = minecraftConsole;
        install-minecraft-service = installMinecraftService;
        update-plugins = updatePlugins;
        default = minecraftServer;
      };

      apps.${system} = {
        minecraft-server = {
          type = "app";
          program = "${minecraftServer}/bin/minecraft-server";
        };
        minecraft-console = {
          type = "app";
          program = "${minecraftConsole}/bin/minecraft-console";
        };
        minecraft-tmux = {
          type = "app";
          program = "${minecraftTmux}/bin/minecraft-tmux";
        };
        install-minecraft-service = {
          type = "app";
          program = "${installMinecraftService}/bin/install-minecraft-service";
        };
        update-plugins = {
          type = "app";
          program = "${updatePlugins}/bin/update-plugins";
        };
      };
    };
}
