# Generated by nix run .#update-plugins.
# Keys match nix-minecraft's servers.<name>.symlinks declaration format.
{ pkgs }:
{
  "plugins/EssentialsX.jar" = pkgs.fetchurl {
    url = "https://cdn.modrinth.com/data/hXiIvTyT/versions/nY6VN1XH/EssentialsX-2.22.0.jar";
    hash = "sha256-vaRoUQWXf8ouIJggqfCtJCdb0QM5CgMjbzjlm/2sWOY=";
  };
  "plugins/ChestsortPlus.jar" = pkgs.fetchurl {
    url = "https://cdn.modrinth.com/data/nIk7yzza/versions/79T540Ud/chestsort-plus-0.4.0.jar";
    hash = "sha256-aQlciEdaxNTroJuQ9Gk5PAWsyEeto58LxfaVd1pKYqo=";
  };
  "plugins/TreeAssist.jar" = pkgs.fetchurl {
    url = "https://slipcor.net/plugins/treeassist/release/latest/TreeAssist.jar";
    hash = "sha256-vSj1Ilbk6U66t4zJ409j1Bl+eyzvlVfPCTmMDWoZsWU=";
  };
  "plugins/SilkSpawners.jar" = pkgs.fetchurl {
    url = "https://cdn.modrinth.com/data/yqj3dcbL/versions/f9lvO5jz/SilkSpawners_v2.jar";
    hash = "sha256-PiS01Zzc8cmq/OCg81dZ6evn3SuwmA20uVJcB7cZ+dI=";
  };
  "plugins/LuckPerms.jar" = pkgs.fetchurl {
    url = "https://cdn.modrinth.com/data/Vebnzrzj/versions/b0mk8uS6/LuckPerms-Bukkit-5.5.71.jar";
    hash = "sha256-Sc7LZvof0ioTMDmkkOnB5QlaI4581m650qFv5siXVQ0=";
  };
  "plugins/InfiniteVillagerTrades.jar" = pkgs.fetchurl {
    url = "https://cdn.modrinth.com/data/7pdfxYHV/versions/evMqQmJi/instantrestock_2.6.4.jar";
    hash = "sha256-YeuPlKme1qDc7z/E/4pY2DAevDt6lMP+mPfj7bPUqD4=";
  };
}
