# Generated by nix run .#update-plugins.
# Keys match nix-minecraft's servers.<name>.symlinks declaration format.
{ pkgs }:
{
  "plugins/EssentialsX.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/hXiIvTyT/versions/nY6VN1XH/EssentialsX-2.22.0.jar"; sha512 = "472ecf71924801723643ca6e1f9931297de5aa0874a544f8a719e2e2f7c81af81ef7bcbd38b6e43f0260a9dae6abe42c97907e70e2430e326ff8cff12ebd61cf"; };
  "plugins/ChestsortPlus.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/nIk7yzza/versions/79T540Ud/chestsort-plus-0.4.0.jar"; sha512 = "7a5d86ff76e6f61d03e81cad132cee5b264baf292c9c0c6db4a309d94e53117f3757a715282696094a09a0e9cb407f2bedc6b7a15e4ed3f62df2cc7086202e12"; };
  "plugins/TreeAssist.jar" = pkgs.fetchurl {
    url = "https://slipcor.net/plugins/treeassist/release/latest/TreeAssist.jar";
    hash = "sha256-vSj1Ilbk6U66t4zJ409j1Bl+eyzvlVfPCTmMDWoZsWU=";
  };
  "plugins/CreeperConduct.jar" = pkgs.fetchurl {
    url = "https://hangarcdn.papermc.io/plugins/TheGreatCodeholio/CreeperConduct/versions/1.2.0/PAPER/CreeperConduct-1.2.0.jar";
    hash = "sha256-4OFo0tBCTPrhfzAipSLWrEC3/wn4vU7FiRZl9T2e2JE=";
  };
  "plugins/Chunky.jar" = pkgs.fetchurl {
    url = "https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.5.3/PAPER/Chunky-Bukkit-1.5.3.jar";
    hash = "sha256-Uw0sdDCpajmVc5G3CIvhRNqjEI92ZYltHCOqjdSvMvM=";
  };
  "plugins/SilkSpawners.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/yqj3dcbL/versions/DeJkR4Fb/SilkSpawners_v2.jar"; sha512 = "e34cee56dbdbcde47d8175156c8fab91cede755223359fa7f508b5ae4ada02523d7d5ce6393fa78a711c8203d9f2811953ef7f7dbfa2540aedbc2577185aaef4"; };
  "plugins/LuckPerms.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/Vebnzrzj/versions/b0mk8uS6/LuckPerms-Bukkit-5.5.71.jar"; sha512 = "188a91f0a543d23bfda32385fca6db63d61e49c8a422bd452a260bd9cbc6a7d7fe45071199e9fca8f3ce43c2b41ee84fd315bd15464577028ff3951a7d4fab27"; };
  "plugins/InfiniteVillagerTrades.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/7pdfxYHV/versions/evMqQmJi/instantrestock_2.6.4.jar"; sha512 = "bbb155e0612d32c546e763759395e0ce62e6480caba236889eafd3ded490a91b6c48cfa3f0a5dba2635689621570d0a802ca0c09786da1f2b500964d8fcd325e"; };
  "plugins/WanderingTrades.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/ZfddU72x/versions/hFXagHpi/WanderingTrades-1.9.5.jar"; sha512 = "4d2547f4cb081f70b39d8f5d7b3dba169ef1c574a273e4a8308f8a91ada7addafc5135454c58f5c321319274ae9c5e87a0c43c0496110e4fbf1b18901e0a7d81"; };
  "plugins/WorldEdit.jar" = pkgs.fetchurl { url = "https://cdn.modrinth.com/data/1u6JkXh5/versions/F5ea2ov3/worldedit-bukkit-7.4.5.jar"; sha512 = "a383492fac6bfb4d43a257dfa7b5fc076aae503a71151b463de4fe80e6f3d5fc11209eaf4097baa115f3febf0adc40ca0a1ecda227b8439b429d0a4ba3a63a4f"; };
}
